### ISSUE TITLE
USER STORY: Admin Register

### ISSUE THREAD

**Issue by tomdu3** [tomdu3/books-for-life#21]
### EPIC: Admin Dashboard

***

### USER STORY
_An explanation of the feature or function, written from the perspective of the end user_

As a ***admin***, I want to ***register myself***, so that I can ***be recognized as an administrator***

***

### ACCEPTANCE CRITERIA

- [x] When  registered, user can designate themselves as administrator.
- [x] Administrator registration will ask  for the approval......
- [x] Upon approval, administrator will receive an email.

***

### TASKS

- [x] Add a checkbox for administrator account on registration form.
- [x] Make a view to inform the current administrators that an admin user want's to register.
- [x] Task 3

***
