### ISSUE TITLE
USER STORY: Delete User

### ISSUE THREAD

**Issue by tomdu3** [tomdu3/books-for-life#22]
### EPIC: <epic>
Admin - USER PROFILE edit

***

### USER STORY
_An explanation of the feature or function, written from the perspective of the end user_

As a ***administrato***, I want to ***be able to delete a user registered to the webiste***, so that I can ***remove the users who didn't behave according to the required rules.***

***

### ACCEPTANCE CRITERIA
_A set of predefined requirements that must be met to meet the user story needs (and mark it as complete)_.

- [x] Admin can click on delete button on User's profile 
- [x] After he clicks, the modal appears to ask him to confirm.
- [x] Upon confirmation, the user is deleted from the database.

***

### TASKS
_A single unit of work broken down from the defined user story_

- [x] make user profile view accessible to admin for every registered user....
- [x] Task 2
- [ ] Task 3

***

### DEPENDENCIES
**EPIC:** <epic>
